name: Deploy spec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 'node'
    - run: npm install
    - run: npm run build
    - name: commit changes
      uses: elstudio/actions-js-build/commit@v3
      with:
        commitMessage: "fixup: [spec] `npm run build`"
